name: AdminToolbox
main: no.runsafe.admintoolbox.AdminToolbox
version: 1.0.@BUILD@
authors: []
depend: []
description: 'Just some tools'
commands:
  colour:
    description: Colours a leather armour item with the supplied hex code
    aliases: [dye]
  author:
    description: Changes the author of a book
  mode:
    description: Allows you to change the players game mode
  give:
    description: Gives a player the items specified.
    aliases: [item, i, give]
  renameitem:
    description: Renames an item in your hand.
  bind:
    description: Allows you to bind commands to a tool.
  bindpermanent:
    description: Allows you to bind commands to a tool in a permanent fashion.
    aliases: [pbind]
  addlore:
    description: Add lore text to an item.
    aliases: [lore]
  clearlore:
    description: Clears an item's lore.
  repair:
    description: Repair the item you are holding.
  kit:
    description: Kit related commands.